messages:
  vanish_enabled: "&8(&b&lXVANISH&8) &bVanish &e-> &cAbilitata&f!"
  vanish_disabled: "&8(&b&lXVANISH&8) &bVanish &e-> &cDisabilitata&f!"
  no_permission: "&8(&b&lXVANISH&8) &cNon hai il permesso per usare questo comando!"
  not_player: "&8(&b&lXVANISH&8) &cSolo i giocatori possono usare questo comando!"
  vanish_list_header: "&8(&b&lXVANISH&8) &bPlayer in vanish &7({count})&7: "
  vanish_list_none: "&8(&b&lXVANISH&8) &cNessun player è in vanish"
  staff_notify_enter: "&8(&b&lXVANISH&8) &e{player} &7è entrato in vanish"
  staff_notify_exit: "&8(&b&lXVANISH&8) &e{player} &7è uscito dalla vanish"
  vanish_effects_enabled: "&8(&b&lXVANISH&8) &bEffetti abilitati!"
  plugin_enabled: "&8(&b&lXVANISH&8) &aPlugin caricato con successo!"
  plugin_disabled: "&8(&b&lXVANISH&8) &cPlugin disabilitato"
  staff_vanished_count: "&8(&b&lXVANISH&8) &bCi sono &e{count} &7staff in vanish"

permissions:
  vanish_use: "xvanish.use"
  vanish_see: "xvanish.see"
  vanish_list: "xvanish.list"

events:
  block_break: true
  block_place: true
  item_drop: true
  item_pickup: true
  entity_damage: true
  player_interact: true
  inventory_click: true
  entity_target: true
  toggle_flight: true
  hide_from_tablist: true